# Generated by Django 6.0.2 on 2026-04-20 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='reels/%Y/%m/')),
                ('file_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image')], max_length=10)),
                ('file_size', models.IntegerField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='media_created_8cc717_idx'), models.Index(fields=['is_active', '-created_at'], name='media_is_acti_fbc461_idx')],
            },
        ),
    ]
